!unquoted procedure $c4_context($id)
'!$context = %loadJSON("context.json")
!$context={"participants" :[
{"id": "c4_helper" , "link": "https://gobravedave.atlassian.net/wiki/x/C4AD"},
{"id": "ea_plantuml" , "link": "https://github.com/gobravedave/Enterprise-Architect/blob/master/README.adoc"},
{"id": "next_project" , "link": "https://modelhelper.home.blog/"}
]
}
!if $id == "#list#"
    Legend bottom 
    | **ID** | **Link** |
    !foreach $part in $context.participants
| $part.id | [[$part.link]] |
    !endfor
    endlegend
!else
    !$context_exist = %false()
    !foreach $part in $context.participants
        !if $part.id == $id
            !$context_exist = %true()
            !if $part_link
            %set_variable_value("$CONTEXT_LINK", "[[" + $part.link + " {click to return to " + $id + " context view}]]")
            !else 
            %set_variable_value("$CONTEXT_LINK", "")
            !endif
        !endif
    !endfor
!endif

!endprocedure

!unquoted procedure $c4_container($id)
'!$container = %loadJSON("container.json")
!$container={"participants" :[
{"id": "c4" ,"label": "C4", "tech": "stdlib", "desc": "Modelling approach for visualising Software Architecture", "contextid": "c4_helper", "link": "https://c4model.com/"},
{"id": "vsc" ,"label": "Visual Studio Code", "tech": "exe", "desc": "Code Editor", "contextid": "c4_helper", "link": "https://code.visualstudio.com/docs"},
{"id": "plantuml" ,"label": "PlantUML", "tech": "VSC Extension", "desc":"Creates UML (and other diagrams types) using plain text scripting language", "contextid": "c4_helper", "link": "https://plantuml.com/"},
{"id": "github" ,"label": "GitHub", "tech": "open source", "desc":"Development Platform", "contextid": "c4_helper", "link": "https://github.com/"}, 
{"id": "arc" ,"label": "Architecture Diagrams" ,"tech": "script" ,"desc": "A set of Diagrams use to capture the architeture of a solution" ,"contextid": "c4_helper" ,"link": "	https://gobravedave.atlassian.net/wiki/x/EoAD"}, 
{"id": "c4_helper" ,"label": "C4 PlantUML Helper Macro" ,"tech": "macro" ,"desc": "helper macros for register C4 elements for resuse in producing C4 type Architecural Diagrams" ,"contextid": "c4_helper" ,"link": "https://github.com/gobravedave/C4-Plantuml-Helper/blob/master/README.adoc"} 
]
}

!if $id == "#list#"
    Legend bottom 
    | **ID** | **Container** | **Techology** | **Description** | **Context ID** | **Link** |
    !foreach $part in $container.participants
| $part.id | $part.label | $part.tech | $part.desc | $part.contextid | [[$part.link]] |
    !endfor
    endlegend
!else
    !$container_exist = %false()
    !foreach $part in $container.participants
        !if $part.id == $id
            !$container_exist = %true()
            %set_variable_value("$CONTAINER_LABEL", $part.label)
            %set_variable_value("$CONTAINER_DESC", $part.desc)
            %set_variable_value("$CONTAINER_TECH", $part.tech)
            !if $part.contextid
                %set_variable_value("$CONTAINER_CONTEXTID", $part.contextid)
            !else 
                %set_variable_value("$CONTAINER_CONTEXTID", "")
            !endif
            !if $part.link
                %set_variable_value("$CONTAINER_LINK", "[[" + $part.link + "{view  " + $id + "}]]")
            !else 
                %set_variable_value("$CONTAINER_LINK", "")
            !endif
        !endif
    !endfor
    !if %not($container_exist)
        %set_variable_value("$CONTAINER_LABEL", "container label")
        %set_variable_value("$CONTAINER_DESC", "container description")
        %set_variable_value("$CONTAINER_TECH", "tech")
        %set_variable_value("$CONTAINER_CONTEXTID", "container context")
        %set_variable_value("$CONTAINER_LINK", "[[add link here]]")
    !endif
!endif
!endprocedure

!unquoted procedure $c4_component($id)
'!$component = %loadJSON("component.json")
!$component={"participants" :[
{"id": "vsc_snippet" ,"label": "C4 PlantUML Snippet" ,"tech": "script" ,"desc": "VSC Code snippets to supporting C4 syntax" ,"containerid": "vsc" ,"link": "add link"},
{"id": "vsc_plant" ,"label": "PlantUML Extension" ,"tech": "ext" ,"desc": "Visual Studio Extension to support writingting PlantUML scripts" ,"containerid": "vsc" ,"link": "https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml"},
{"id": "git_c4" ,"label": "C4 PlantUML Stdlib" ,"tech": "script" ,"desc": "C4 Object Definitions and Styles " ,"containerid": "github" ,"link": "https://github.com/RicardoNiepel/C4-PlantUML"}, 
{"id": "git_arc" ,"label": "C4 PlantUML Diagram Script" ,"tech": "script" ,"desc": "C4 Diagram Script" ,"containerid": "github" ,"link": "https://github.com/gobravedave/C4-Plantuml-Helper/blob/master/demo.puml"}, 
{"id": "git_svg" ,"label": "C4 PlantUML Diagram" ,"tech": "svg" ,"desc": "Rendered C4 Diagram" ,"containerid": "github" ,"link": ""}, 
{"id": "git_c4_helper" ,"label": "C4 PlantUML Helper Macro" ,"tech": "macro" ,"desc": "helper macros for scripting C4 Diagrms using PlantUML" ,"containerid": "c4_helper" ,"link": "https://gobravedave.github.io/C4-Plantuml-Helper/component.html"} 
]
}
!if $id == "#list#"
    Legend bottom 
    | **ID** | **Component** | **Techology** | **Description** | **Container ID** | **Link** |
    !foreach $part in $component.participants
| $part.id | $part.label | $part.tech | $part.desc | $part.containerid | [[$part.link]] |
    !endfor
    endlegend
!else
    !$component_exist = %false()
    !foreach $part in $component.participants
        !if $part.id == $id
            !$component_exist = %true()
            %set_variable_value("$COMPONENT_LABEL", $part.label)
            %set_variable_value("$COMPONENT_TECH", $part.tech)
            %set_variable_value("$COMPONENT_DESC", $part.desc)
            !if $part.containerid
                %set_variable_value("$COMPONENT_CONTAINERID", $part.containerid)
            !else 
                %set_variable_value("$COMPONENT_CONTAINERID", "")
            !endif
            !if $part.link
                %set_variable_value("$COMPONENT_LINK", "[[" + $part.link + "{view  " + $id + "}]]")
            !else 
                %set_variable_value("$COMPONENT_LINK", "")
            !endif
        !endif
    !endfor
    !if %not($component_exist)
        %set_variable_value("$COMPONENT_LABEL", "component label")
        %set_variable_value("$COMPONENT_DESC", "component description")
        %set_variable_value("$COMPONENT_TECH", "tchnology")
        %set_variable_value("$COMPONENT_CONTAINERID", "component container")
        %set_variable_value("$COMPONENT_LINK", "[[add component link]]")
    !endif
!endif

!endprocedure

!unquoted procedure $container($id)

'If C4 diagram type is set to Container, resolve URL by associated context identifer 
$c4_container($id)
!if $C4_LEVEL == "CONTAINER"
    $c4_context($CONTAINER_CONTEXTID)
    !if $INCLUDE_DESC == "Y"
        Container($id, $CONTAINER_LABEL, $CONTAINER_TECH, $CONTAINER_DESC) $CONTEXT_LINK {
    !else
        Container($id, $CONTAINER_LABEL, $CONTAINER_TECH) $CONTEXT_LINK {
    !endif
!else
    !if $INCLUDE_DESC == "Y"
        Container($id, $CONTAINER_LABEL, $CONTAINER_TECH, $CONTAINER_DESC) $CONTAINER_LINK {
    !else
        Container($id, $CONTAINER_LABEL, $CONTAINER_TECH) $CONTAINER_LINK {
    !endif
!endif
!endprocedure

!unquoted procedure $containerDb($id)
'If C4 diagram type is set to Container, resolve URL by associated context identifer 
$c4_container($id)
!if $C4_LEVEL == "CONTAINER"
    $c4_context($CONTAINER_CONTEXTID)
    !if $INCLUDE_DESC == "Y"
        ContainerDb($id, $CONTAINER_LABEL, $CONTAINER_TECH, $CONTAINER_DESC) $CONTEXT_LINK {
    !else
        ContainerDb($id, $CONTAINER_LABEL, $CONTAINER_TECH) $CONTEXT_LINK {
    !endif
!else
    !if $INCLUDE_DESC == "Y"
        ContainerDb($id, $CONTAINER_LABEL, $CONTAINER_TECH, $CONTAINER_DESC) $CONTAINER_LINK {
    !else
        ContainerDb($id, $CONTAINER_LABEL, $CONTAINER_TECH) $CONTAINER_LINK {
    !endif
!endif

!endprocedure

!unquoted procedure $context_list()
'list all registered contexts
$c4_context(#list#)
!endprocedure

!unquoted procedure $container_list()
'list all registered containers
$c4_container(#list#)
!endprocedure

!unquoted procedure $component_list()
'list all registered components
$c4_component(#list#)
!endprocedure

!unquoted procedure $container_boundary($id)

$c4_container($id)
!if $C4_LEVEL == "CONTAINER"
    $c4_context($CONTAINER_CONTEXTID)
    Container_Boundary($id, $CONTAINER_LABEL) $CONTEXT_LINK {
!else
    Container_Boundary($id, $CONTAINER_LABEL) $CONTAINER_LINK {
!endif

!endprocedure

!unquoted procedure $component($id)

$c4_component($id)
!if $C4_LEVEL == "COMPONENT"
    $c4_container($COMPONENT_CONTAINERID)
    !if $INCLUDE_DESC == "Y"
        Component($id, $COMPONENT_LABEL, $COMPONENT_TECH, $COMPONENT_DESC) $CONTAINER_LINK {
    !else
        Component($id, $COMPONENT_LABEL, $COMPONENT_TECH) $CONTAINER_LINK {
    !endif
!else
    !if $INCLUDE_DESC == "Y"
        Component($id, $COMPONENT_LABEL, $COMPONENT_TECH, $COMPONENT_DESC) $COMPONENT_LINK {
    !else
        Component($id, $COMPONENT_LABEL, $COMPONENT_TECH) $COMPONENT_LINK {
    !endif
!endif

!endprocedure

!unquoted procedure $componentDb($id)

$c4_component($id)
!if $C4_LEVEL == "COMPONENT"
    $c4_container($COMPONENT_CONTAINERID)
    !if $INCLUDE_DESC == "Y"
        ComponentDb($id, $COMPONENT_LABEL, $COMPONENT_TECH, $COMPONENT_DESC) $CONTAINER_LINK { 
    !else
        ComponentDb($id, $COMPONENT_LABEL, $COMPONENT_TECH) $CONTAINER_LINK {
    !endif
!else
    !if $INCLUDE_DESC == "Y"
        ComponentDb($id, $COMPONENT_LABEL, $COMPONENT_TECH, $COMPONENT_DESC) $COMPONENT_LINK {
    !else
        ComponentDb($id, $COMPONENT_LABEL, $COMPONENT_TECH) $COMPONENT_LINK {
    !endif
!endif

!endprocedure
