!unquoted procedure $c4_context($id)
!$context = %load_json("context.json")


!if $id == "#list#"
    skinparam NoteBackgroundColor #white
    note as c4_contexts  
    | **ID** | **Label** | **Description** | **Link** |
    !foreach $part in $context.participants
    | $part.id | $part.label || $part.desc | [[$part.link]] |
    !endfor
    end note
!else
    !$context_exist = %false()
    !foreach $part in $context.participants
        !if $part.id == $id
            !$context_exist = %true()
            %set_variable_value("$CONTEXT_DESC", $part.desc)
            %set_variable_value("$CONTEXT_LABEL", $part.label)
            !if $part.link
            %set_variable_value("$CONTEXT_LINK", "[[" + $part.link + " {click to return to " + $id + " context view}]]")
            !else 
            %set_variable_value("$CONTEXT_LINK", "")
            !endif
        !endif
    !endfor
    !if %not($context_exist)
        %set_variable_value("$CONTEXT_LABEL", "context label")
        %set_variable_value("$CONTEXT_DESC", "context description")
        %set_variable_value("$CONTEXT_LINK", "[[add link here]]")
    !endif
!endif

!endprocedure

!unquoted procedure $c4_container($id)
!$container = %load_json("container.json")

!if $id == "#list#"
    skinparam NoteBackgroundColor #white
    note as c4_containers  
    | **ID** | **Container** | **Techology** | **Description** | **Link** |
    !foreach $part in $container.participants
    | $part.id | $part.label | $part.tech | $part.desc | [[$part.link]] |
    !endfor
    end note
!else
    !$container_exist = %false()
    !foreach $part in $container.participants
        !if $part.id == $id
            !$container_exist = %true()
            %set_variable_value("$CONTAINER_LABEL", $part.label)
            %set_variable_value("$CONTAINER_DESC", $part.desc)
            %set_variable_value("$CONTAINER_TECH", $part.tech)
            !if $part.contextid
                %set_variable_value("$CONTAINER_CONTEXTID", $part.contextid)
            !else 
                %set_variable_value("$CONTAINER_CONTEXTID", "")
            !endif
            !if $part.link
                %set_variable_value("$CONTAINER_LINK", "[[" + $part.link + "{view  " + $id + "}]]")
            !else 
                %set_variable_value("$CONTAINER_LINK", "")
            !endif
        !endif
    !endfor
    !if %not($container_exist)
        %set_variable_value("$CONTAINER_LABEL", "container label")
        %set_variable_value("$CONTAINER_DESC", "container description")
        %set_variable_value("$CONTAINER_TECH", "tech")
        %set_variable_value("$CONTAINER_CONTEXTID", "container context")
        %set_variable_value("$CONTAINER_LINK", "[[add link here]]")
    !endif
!endif
!endprocedure

' !procedure $c4_component($id)
!unquoted procedure $c4_component($id)
!$component = %load_json("component.json")

!if $id == "#list#"
    skinparam NoteBackgroundColor #white
    note as c4_components
    | **ID** | **Component** | **Techology** | **Description** | **Container ID** | **Link** |
    !foreach $part in $component.participants
    | $part.id | $part.label | $part.tech | $part.desc | $part.containerid | [[$part.link]] |
    !endfor
    end note
!else
    !$component_exist = %false()
    !foreach $part in $component.participants
        !if $part.id == $id
            !$component_exist = %true()
            %set_variable_value("$COMPONENT_LABEL", $part.label)
            %set_variable_value("$COMPONENT_TECH", $part.tech)
            %set_variable_value("$COMPONENT_DESC", $part.desc)
            !if $part.containerid
                %set_variable_value("$COMPONENT_CONTAINERID", $part.containerid)
            !else 
                %set_variable_value("$COMPONENT_CONTAINERID", "")
            !endif
            !if $part.link
                %set_variable_value("$COMPONENT_LINK", "[[" + $part.link + "{view  " + $id + "}]]")
            !else 
                %set_variable_value("$COMPONENT_LINK", "")
            !endif
        !endif
    !endfor
    !if %not($component_exist)
        %set_variable_value("$COMPONENT_LABEL", "component label")
        %set_variable_value("$COMPONENT_DESC", "component description")
        %set_variable_value("$COMPONENT_TECH", "tchnology")
        %set_variable_value("$COMPONENT_CONTAINERID", "component container")
        %set_variable_value("$COMPONENT_LINK", "[[add component link]]")
    !endif
!endif

!endprocedure

!unquoted procedure $container($id)

'If C4 diagram type is set to Container, resolve URL by associated context identifer 
$c4_container($id)
!if $C4_LEVEL == "CONTAINER"
    $c4_context($CONTAINER_CONTEXTID)
    !if $INCLUDE_DESC == "Y"
        Container($id, $CONTAINER_LABEL, $CONTAINER_TECH, $CONTAINER_DESC) $CONTEXT_LINK {
    !else
        Container($id, $CONTAINER_LABEL, $CONTAINER_TECH) $CONTEXT_LINK {
    !endif
!else
    !if $INCLUDE_DESC == "Y"
        Container($id, $CONTAINER_LABEL, $CONTAINER_TECH, $CONTAINER_DESC) $CONTAINER_LINK {
    !else
        Container($id, $CONTAINER_LABEL, $CONTAINER_TECH) $CONTAINER_LINK {
    !endif
!endif
!endprocedure

!unquoted procedure $containerDb($id)
'If C4 diagram type is set to Container, resolve URL by associated context identifer 
$c4_container($id)
!if $C4_LEVEL == "CONTAINER"
    $c4_context($CONTAINER_CONTEXTID)
    !if $INCLUDE_DESC == "Y"
        ContainerDb($id, $CONTAINER_LABEL, $CONTAINER_TECH, $CONTAINER_DESC) $CONTEXT_LINK {
    !else
        ContainerDb($id, $CONTAINER_LABEL, $CONTAINER_TECH) $CONTEXT_LINK {
    !endif
!else
    !if $INCLUDE_DESC == "Y"
        ContainerDb($id, $CONTAINER_LABEL, $CONTAINER_TECH, $CONTAINER_DESC) $CONTAINER_LINK {
    !else
        ContainerDb($id, $CONTAINER_LABEL, $CONTAINER_TECH) $CONTAINER_LINK {
    !endif
!endif

!endprocedure

!unquoted procedure $context_list()
'list all registered contexts
$c4_context(#list#)
!endprocedure

!unquoted procedure $container_list()
'list all registered containers
$c4_container(#list#)
!endprocedure

!unquoted procedure $component_list()
'list all registered components
$c4_component(#list#)
!endprocedure

!unquoted procedure $container_boundary($id)

$c4_container($id)
!if $C4_LEVEL == "CONTAINER"
    $c4_context($CONTAINER_CONTEXTID)
    Container_Boundary($id, $CONTAINER_LABEL) $CONTEXT_LINK {
!else
    Container_Boundary($id, $CONTAINER_LABEL) $CONTAINER_LINK {
!endif

!endprocedure

!unquoted procedure $component($id)

$c4_component($id)
!if $C4_LEVEL == "COMPONENT"
    $c4_container($COMPONENT_CONTAINERID)
    !if $INCLUDE_DESC == "Y"
        Component($id, $COMPONENT_LABEL, $COMPONENT_TECH, $COMPONENT_DESC) $CONTAINER_LINK {
    !else
        Component($id, $COMPONENT_LABEL, $COMPONENT_TECH) $CONTAINER_LINK {
    !endif
!else
    !if $INCLUDE_DESC == "Y"
        Component($id, $COMPONENT_LABEL, $COMPONENT_TECH, $COMPONENT_DESC) $COMPONENT_LINK {
    !else
        Component($id, $COMPONENT_LABEL, $COMPONENT_TECH) $COMPONENT_LINK {
    !endif
!endif

!endprocedure

!unquoted procedure $componentDb($id)

$c4_component($id)
!if $C4_LEVEL == "COMPONENT"
    $c4_container($COMPONENT_CONTAINERID)
    !if $INCLUDE_DESC == "Y"
        ComponentDb($id, $COMPONENT_LABEL, $COMPONENT_TECH, $COMPONENT_DESC) $CONTAINER_LINK { 
    !else
        ComponentDb($id, $COMPONENT_LABEL, $COMPONENT_TECH) $CONTAINER_LINK {
    !endif
!else
    !if $INCLUDE_DESC == "Y"
        ComponentDb($id, $COMPONENT_LABEL, $COMPONENT_TECH, $COMPONENT_DESC) $COMPONENT_LINK {
    !else
        ComponentDb($id, $COMPONENT_LABEL, $COMPONENT_TECH) $COMPONENT_LINK {
    !endif
!endif

!endprocedure
