@startuml
!function $get_c4_diagram($id)

!log get_c4_diagram-> $id

%set_variable_value($diagram_exist, %false())
!foreach $diagram in $diagrams.c4DiagramRegistry.diagrams
    !if $diagram.c4Id == $id
        %set_variable_value($diagram_exist, %true())
        ' !log got a hit
        ' !log $diagram
        !return $diagram
    !endif
!endfor

!if $diagram_exist == %false()
    'return eror response if json file not found
    ' !log diagram $id not found
    !return ""
!endif
    
!endfunction

!function $get_c4_object($id)
'!log get_c4_object: $id
%set_variable_value($object_exist, %false())
!foreach $object in $objects.c4ObjectRegistry.objects
    ' !log $object.c4objectID equal to $id?
    !if $object.c4objectID == $id
        %set_variable_value($object_exist, %true())
        ' !log got a hit
        ' !log $object
        !return $object
    !endif
!endfor

!if $object_exist == %false()
    ' !log object $id not found
    !return ""
!endif

!endfunction

!unquoted procedure $c4_diagram($id)
' !log c4_diagram: $id
!global $diagrams = %load_json("C4_diagrams.json")
!global $objects = %load_json("C4_objects.json")
!global $diagramObjects = "~"

!$diagram = $get_c4_diagram($id)
!if  %json_key_exists($diagram, "title")
    title $diagram.title - $C4_DIAGRAM_TYPE Diagram
!else 
    title $id diagram not found in C4_Diagrams.json
!endif

!foreach $contain in $diagram.contains
    $writeout_c4_object($contain)
!endfor

!log here are all the objects on the diagram: %get_variable_value($diagramObjects)
!$list = %splitstr(%get_variable_value($diagramObjects), "~")
!foreach $item in $list
    $writeout_c4_relationships($item)
!endfor

SHOW_LEGEND()

!endprocedure

!unquoted procedure $writeout_c4_object($id)
'output associated diagram objects (diagram dependant)
'   Context view.. Person, Person_Ext, System, System_Ext, Enterprise_Boundary
'   Container View.. System Boundary, Container
'   Componenet View.. Container Boundary and Components
!log writeout_c4_object: $id

!$object = $get_c4_object($id)
!if $C4_DIAGRAM_TYPE == "Context"
    !if %not (%json_key_exists($object, "c4objectName"))
System($id, "$id")
    !elseif $object.c4objectType == "Person"
        !$result = $add_id_list(%get_variable_value($diagramObjects), $id)
Person($object.c4objectID, "$object.c4objectName", $c4h_descr($object))
    !elseif $object.c4objectType == "Person_Ext"
        !$result = $add_id_list(%get_variable_value($diagramObjects), $id)
Person_Ext($object.c4objectID, "$object.c4objectName", $c4h_descr($object))
    !elseif $object.c4objectType == "System"
        !$result = $add_id_list(%get_variable_value($diagramObjects), $id)
System($object.c4objectID, "$object.c4objectName", $c4h_descr($object))
    !elseif $object.c4objectType == "System_Ext"
        !$result = $add_id_list(%get_variable_value($diagramObjects), $id)
System_Ext($object.c4objectID, "$object.c4objectName", $c4h_descr($object))
    !elseif $object.c4objectType == "Enterprise_Boundary"
Enterprise_Boundary($object.c4objectID, "$object.c4objectName") {
        !foreach $contain in $object.contains
            !log add $contain to $object.c4objectID
            $writeout_c4_object($contain)
        !endfor
}                    
    !endif
!elseif $C4_DIAGRAM_TYPE == "Container"
    !if %not (%json_key_exists($object, "c4objectName"))
Container($id, "$id")
    !elseif $object.c4objectType == "Person"
'hide $object.c4objectID
'        !$result = $add_id_list(%get_variable_value($diagramObjects), $id)
'Person($object.c4objectID, "$object.c4objectName", $c4h_descr($object))
    !elseif $object.c4objectType == "Person_Ext"
'        !$result = $add_id_list(%get_variable_value($diagramObjects), $id)
'Person_Ext($object.c4objectID, "$object.c4objectName", $c4h_descr($object))
    !elseif $object.c4objectType == "Enterprise_Boundary"
Enterprise_Boundary($object.c4objectID, "$object.c4objectName",$c4h_descr($object)) {
        !foreach $contain in $object.contains
'            !log add $contain 
            $writeout_c4_object($contain)
        !endfor
}
    !elseif $object.c4objectType == "System" || $object.c4objectType == "System_Ext"
        !if %size($object.contains) > 0
            !log add system boundary
System_Boundary($object.c4objectID, "$object.c4objectName",$c4h_descr($object)) {
            !foreach $contain in $object.contains
'                !log add $contain to system
                $writeout_c4_object($contain)
            !endfor
}
            !log end of system boundary
        !else
            ' !log add container $object.c4objectID
        !$result = $add_id_list(%get_variable_value($diagramObjects), $id)
Container($object.c4objectID, "$object.c4objectName", $c4h_techn($object), $c4h_descr($object))
        !endif      
    !elseif $object.c4objectType == "Container"
            ' !log add container $object.c4objectID
        !$result = $add_id_list(%get_variable_value($diagramObjects), $id)
Container($object.c4objectID, "$object.c4objectName", $c4h_techn($object), $c4h_descr($object))
    !elseif $object.c4objectType == "ContainerDb"
            ' !log add container $object.c4objectID
        !$result = $add_id_list(%get_variable_value($diagramObjects), $id)
ContainerDb($object.c4objectID, "$object.c4objectName", $c4h_techn($object), $c4h_descr($object))
    !endif
!elseif $C4_DIAGRAM_TYPE == "Component"
!endif
!endprocedure

!unquoted procedure $writeout_c4_relationships($id)
!log writeout_c4_relationships($id)
!$object = $get_c4_object($id)

!foreach $relationship in $object.relationships
    !if  %strpos(%get_variable_value($diagramObjects),$relationship.c4relationshipTo) > 0
        !if $relationship.c4relationshipType == "Rel_R"
Rel_R($object.c4objectID, $relationship.c4relationshipTo,"$relationship.c4relationshipDesc")
        !elseif $relationship.c4relationshipType == "Rel_L"
Rel_L($object.c4objectID, $relationship.c4relationshipTo,"$relationship.c4relationshipDesc")
        !elseif $relationship.c4relationshipType == "Rel_U"
Rel_U($object.c4objectID, $relationship.c4relationshipTo,"$relationship.c4relationshipDesc")
        !elseif $relationship.c4relationshipType == "Rel_D"
Rel_D($object.c4objectID, $relationship.c4relationshipTo,"$relationship.c4relationshipDesc")
        !elseif $relationship.c4relationshipType == "Lay_L"
Lay_L($object.c4objectID, $relationship.c4relationshipTo)
        !elseif $relationship.c4relationshipType == "Lay_R"
Lay_R($object.c4objectID, $relationship.c4relationshipTo)
        !elseif $relationship.c4relationshipType == "Lay_U"
Lay_U($object.c4objectID, $relationship.c4relationshipTo)
        !elseif $relationship.c4relationshipType == "Lay_D"
Lay_D($object.c4objectID, $relationship.c4relationshipTo)
        !else
Rel($object.c4objectID, $relationship.c4relationshipTo,"$relationship.c4relationshipDesc")
        !endif
    !endif
!endfor

!endprocedure

!unquoted function $add_id_list($idlist, $id)
!if %strpos($idlist, $id) > 0
    !return %false()
!else 
    %set_variable_value($diagramObjects, ($idlist + "~"+$id+"~"))
    !return  %true()
!endif

!endfunction

!function $c4h_descr($object)
!if $INCLUDE_DESC == "Y"
    !return  "$descr=" $object.c4objectDesc
!else 
    !return ""
!endif
!endfunction

!function $c4h_techn($object)
    !if %json_key_exists($object, "c4objectTech")
        !return  "$techn=" $object.c4objectTech
    !else 
        !return  "$techn=" $object.c4objectType
    !endif
!endfunction

'v1 code below.. refactor based on updates json structure
!unquoted procedure $c4_context($id)
!$context = %load_json("context.json")

!if $id == "#list#"
    skinparam NoteBackgroundColor #white
    note as c4_contexts  
    | **ID** | **Label** | **Description** | **Link** |
    !foreach $part in $context.participants
    | $part.id | $part.label || $part.desc | [[$part.link]] |
    !endfor
    end note
!else
    !$context_exist = %false()
    !foreach $part in $context.participants
        !if $part.id == $id
            !$context_exist = %true()
            %set_variable_value("$CONTEXT_DESC", $part.desc)
            %set_variable_value("$CONTEXT_LABEL", $part.label)
            !if $part.link
            %set_variable_value("$CONTEXT_LINK", "[[" + $part.link + " {click to return to " + $id + " context view}]]")
            !else 
            %set_variable_value("$CONTEXT_LINK", "")
            !endif
        !endif
    !endfor
    !if %not($context_exist)
        %set_variable_value("$CONTEXT_LABEL", "context label")
        %set_variable_value("$CONTEXT_DESC", "context description")
        %set_variable_value("$CONTEXT_LINK", "[[add link here]]")
    !endif
!endif

!endprocedure

!unquoted procedure $c4_container($id)
!$container = %load_json("container.json")

!if $id == "#list#"
    skinparam NoteBackgroundColor #white
    note as c4_containers  
    | **ID** | **Container** | **Techology** | **Description** | **Link** |
    !foreach $part in $container.participants
    | $part.id | $part.label | $part.tech | $part.desc | [[$part.link]] |
    !endfor
    end note
!else
    !$container_exist = %false()
    !foreach $part in $container.participants
        !if $part.id == $id
            !$container_exist = %true()
            %set_variable_value("$CONTAINER_LABEL", $part.label)
            %set_variable_value("$CONTAINER_DESC", $part.desc)
            %set_variable_value("$CONTAINER_TECH", $part.tech)
            !if $part.contextid
                %set_variable_value("$CONTAINER_CONTEXTID", $part.contextid)
            !else 
                %set_variable_value("$CONTAINER_CONTEXTID", "")
            !endif
            !if $part.link
                %set_variable_value("$CONTAINER_LINK", "[[" + $part.link + "{view  " + $id + "}]]")
            !else 
                %set_variable_value("$CONTAINER_LINK", "")
            !endif
        !endif
    !endfor
    !if %not($container_exist)
        %set_variable_value("$CONTAINER_LABEL", "container label")
        %set_variable_value("$CONTAINER_DESC", "container description")
        %set_variable_value("$CONTAINER_TECH", "tech")
        %set_variable_value("$CONTAINER_CONTEXTID", "container context")
        %set_variable_value("$CONTAINER_LINK", "[[add link here]]")
    !endif
!endif
!endprocedure

!unquoted procedure $c4_component($id)
!$component = %load_json("component.json")

!if $id == "#list#"
    skinparam NoteBackgroundColor #white
    note as c4_components
    | **ID** | **Component** | **Techology** | **Description** | **Container ID** | **Link** |
    !foreach $part in $component.participants
    | $part.id | $part.label | $part.tech | $part.desc | $part.containerid | [[$part.link]] |
    !endfor
    end note
!else
    !$component_exist = %false()
    !foreach $part in $component.participants
        !if $part.id == $id
            !$component_exist = %true()
            %set_variable_value("$COMPONENT_LABEL", $part.label)
            %set_variable_value("$COMPONENT_TECH", $part.tech)
            %set_variable_value("$COMPONENT_DESC", $part.desc)
            !if $part.containerid
                %set_variable_value("$COMPONENT_CONTAINERID", $part.containerid)
            !else 
                %set_variable_value("$COMPONENT_CONTAINERID", "")
            !endif
            !if $part.link
                %set_variable_value("$COMPONENT_LINK", "[[" + $part.link + "{view  " + $id + "}]]")
            !else 
                %set_variable_value("$COMPONENT_LINK", "")
            !endif
        !endif
    !endfor
    !if %not($component_exist)
        %set_variable_value("$COMPONENT_LABEL", "component label")
        %set_variable_value("$COMPONENT_DESC", "component description")
        %set_variable_value("$COMPONENT_TECH", "tchnology")
        %set_variable_value("$COMPONENT_CONTAINERID", "component container")
        %set_variable_value("$COMPONENT_LINK", "[[add component link]]")
    !endif
!endif

!endprocedure

!unquoted procedure $container($id)

'If C4 diagram type is set to Container, resolve URL by associated context identifer 
$c4_container($id)
!if $C4_LEVEL == "CONTAINER"
    $c4_context($CONTAINER_CONTEXTID)
    !if $INCLUDE_DESC == "Y"
        Container($id, $CONTAINER_LABEL, $CONTAINER_TECH, $CONTAINER_DESC) $CONTEXT_LINK {
    !else
        Container($id, $CONTAINER_LABEL, $CONTAINER_TECH) $CONTEXT_LINK {
    !endif
!else
    !if $INCLUDE_DESC == "Y"
        Container($id, $CONTAINER_LABEL, $CONTAINER_TECH, $CONTAINER_DESC) $CONTAINER_LINK {
    !else
        Container($id, $CONTAINER_LABEL, $CONTAINER_TECH) $CONTAINER_LINK {
    !endif
!endif
!endprocedure

!unquoted procedure $containerDb($id)
'If C4 diagram type is set to Container, resolve URL by associated context identifer 
$c4_container($id)
!if $C4_LEVEL == "CONTAINER"
    $c4_context($CONTAINER_CONTEXTID)
    !if $INCLUDE_DESC == "Y"
        ContainerDb($id, $CONTAINER_LABEL, $CONTAINER_TECH, $CONTAINER_DESC) $CONTEXT_LINK {
    !else
        ContainerDb($id, $CONTAINER_LABEL, $CONTAINER_TECH) $CONTEXT_LINK {
    !endif
!else
    !if $INCLUDE_DESC == "Y"
        ContainerDb($id, $CONTAINER_LABEL, $CONTAINER_TECH, $CONTAINER_DESC) $CONTAINER_LINK {
    !else
        ContainerDb($id, $CONTAINER_LABEL, $CONTAINER_TECH) $CONTAINER_LINK {
    !endif
!endif

!endprocedure

!unquoted procedure $context_list()
'list all registered contexts
$c4_context(#list#)
!endprocedure

!unquoted procedure $container_list()
'list all registered containers
$c4_container(#list#)
!endprocedure

!unquoted procedure $component_list()
'list all registered components
$c4_component(#list#)
!endprocedure

!unquoted procedure $container_boundary($id)

$c4_container($id)
!if $C4_LEVEL == "CONTAINER"
    $c4_context($CONTAINER_CONTEXTID)
    Container_Boundary($id, $CONTAINER_LABEL) $CONTEXT_LINK {
!else
    Container_Boundary($id, $CONTAINER_LABEL) $CONTAINER_LINK {
!endif

!endprocedure

!unquoted procedure $component($id)

$c4_component($id)
!if $C4_LEVEL == "COMPONENT"
    $c4_container($COMPONENT_CONTAINERID)
    !if $INCLUDE_DESC == "Y"
        Component($id, $COMPONENT_LABEL, $COMPONENT_TECH, $COMPONENT_DESC) $CONTAINER_LINK {
    !else
        Component($id, $COMPONENT_LABEL, $COMPONENT_TECH) $CONTAINER_LINK {
    !endif
!else
    !if $INCLUDE_DESC == "Y"
        Component($id, $COMPONENT_LABEL, $COMPONENT_TECH, $COMPONENT_DESC) $COMPONENT_LINK {
    !else
        Component($id, $COMPONENT_LABEL, $COMPONENT_TECH) $COMPONENT_LINK {
    !endif
!endif

!endprocedure

!unquoted procedure $componentDb($id)

$c4_component($id)
!if $C4_LEVEL == "COMPONENT"
    $c4_container($COMPONENT_CONTAINERID)
    !if $INCLUDE_DESC == "Y"
        ComponentDb($id, $COMPONENT_LABEL, $COMPONENT_TECH, $COMPONENT_DESC) $CONTAINER_LINK { 
    !else
        ComponentDb($id, $COMPONENT_LABEL, $COMPONENT_TECH) $CONTAINER_LINK {
    !endif
!else
    !if $INCLUDE_DESC == "Y"
        ComponentDb($id, $COMPONENT_LABEL, $COMPONENT_TECH, $COMPONENT_DESC) $COMPONENT_LINK {
    !else
        ComponentDb($id, $COMPONENT_LABEL, $COMPONENT_TECH) $COMPONENT_LINK {
    !endif
!endif

!endprocedure
