@startuml demo_context_view
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/gobravedave/C4-Plantuml-Helper/master/C4_helper.iuml
' !include ../C4-PlantUML-master/C4_Component.puml
' !include ../C4-Plantuml-Helper/C4_helper.iuml

Title \nC4 Model Helper Context View\n  
%set_variable_value("$C4_LEVEL", "CONTEXT")
%set_variable_value("$INCLUDE_DESC", "Y")

Person(tw, "Technical Writer", "Produces Software Architecture Documentation")
$container(vsc)
}
$container(c4)
}
$container(plantuml)
}
$container(arc)
}
$container(c4_helper)
}

tw --> vsc :uses
vsc -> arc :creates
plantuml -> vsc : includes
arc <-- c4 :includes
arc <- c4_helper :includes

@enduml
