@startuml demo_container_view
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/gobravedave/C4-Plantuml-Helper/master/C4_helper.iuml
' !include ../C4-PlantUML-master/C4_Component.puml
' !include ../C4-Plantuml-Helper/C4_helper.iuml
Title \nC4 Model Helper Container View\n 
%set_variable_value("$C4_LEVEL", "CONTAINER")
%set_variable_value("$INCLUDE_DESC", "Y")

$container_boundary(vsc)
	$component(vsc_plant)
	}
}

$container_boundary(plantuml)
	Component(jar, "plantuml.jar", "java")		
}
$container_boundary(github)
	$component(git_arc)
	}
	$component(git_c4)
	}
	$component(git_c4_helper)
	}
	$component(git_svg)
	}
}
jar --> vsc_plant :references
vsc_plant <-- git_arc : processes
vsc_plant --> git_svg :renders
git_c4 -U-> git_arc :includes
git_c4_helper -U-> git_arc :includes

@enduml