@startuml C4 Model Helper Context View
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml
!include C4_helper.iuml
'Title C4 Model Helper 
%set_variable_value("$C4_LEVEL", "CONTEXT")
%set_variable_value("$INCLUDE_DESC", "Y")

Boundary(context, "C4 PlantUML Context"){
	Person(tw, "Technical Writer", "Produces Software Architecture Documentation")
	$container(vsc)
	}
	$container(c4)
	}
	$container(plantuml)
	}
	$container(github)
	}
	Rel_Right(tw, vsc, "uses")
	Rel_Right(vsc, github, "architecture \nmodel")
	Rel_Up(plantuml, vsc, "extended \nto support")
	Rel_Left(c4, plantuml, "extended \nto support")
}

@enduml

@startuml C4 Model Helper Container View
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml
!include C4_helper.iuml
Title C4 Model Helper Container View 
%set_variable_value("$C4_LEVEL", "CONTAINER")
'%set_variable_value("$INCLUDE_DESC", "Y")

$container_boundary(vsc)
	$component(vsc_plant)
	}
	$component(vsc_snippet)
	}
}

$container_boundary(plantuml)
	Component(jar, "plantuml.jar", "java")		
}
$container_boundary(github)
	$component(git_c4)
	}
	$component(git_c4_helper)
	}
}
Rel_Right(jar, vsc_plant, "references")
Rel_Up(git_c4, vsc_plant, "includes")
Rel_Up(git_c4_helper, vsc_plant, "includes")
Rel_Up(git_c4_helper, vsc_snippet, "installed from")

@enduml

@startuml C4 Model Helper Component View
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml
!include C4_helper.iuml
Title C4 Model Helper Component View 
%set_variable_value("$C4_LEVEL", "COMPONENT")
'%set_variable_value("$INCLUDE_DESC", "Y")

$component(git_c4_helper)
	Component(c4ctxr, "Context Registry ", "json", "list of registered contexts")
	Component(c4conr, "Container Registry ", "json", "list of registered containers")
	Component(c4comr, "Component Registry ", "json", "list of registered components")
	Component(c4ctx, "Locate Context ", "script", "locates context by id and returns values")
	Component(c4con, "Locate Container", "script", "locates container by id and returns values")
	Component(c4com, "Locate Component", "script", "locates component by id and returns values")
	Component(c4ctxl, "Context Legend ", "script", "creates a legend using the context registery")
	Component(c4conl, "Container Legend ", "script", "creates a legend using the container registery")
	Component(c4coml, "Component Legend ", "script", "creates a legend using the component registery")
}

Rel_Up(c4ctx, c4ctxr, "get by context id")
Rel_Up(c4ctxl, c4ctx, "get all")
Rel_Up(c4con, c4conr, "get by container id")
Rel_Up(c4conl, c4con, "get all")
Rel_Up(c4com, c4comr, "get by component id")
Rel_Up(c4coml, c4com, "get all")
Rel_Left(c4com, c4con, "get container by id")
Rel_Left(c4con, c4ctx, "get context by id")
@enduml

@startuml C4 Model Helper Container List
Title C4 Model Helper Container List 
!include C4_helper.iuml
$container_list()
@enduml

@startuml C4 Model Helper Component List
Title C4 Model Helper Component List 
!include C4_helper.iuml
$component_list()
@enduml