= Readme
:imagesdir: ./docs

= C4 PlantUML Helper Macro

Getting up to speed with C4 is easy peasy and before you know it you have more diagram scripts than you can shake a stick at.

The issue then becomes:

* how do you standardise on alias and label names used?
* how do you pickup and maintain common descriptions?
* how easy is it to add navigational links as the C4 maker had intended?
* easily find, reuse, extend modelled objects
* provide reports/dashboards of usage and dependancies
* How do we maintain and integrate all these scripts so to produce a “Model” of the architecture.

C4_Plantuml_Helper to the rescue.

== Context 

image::demo context view.svg[Context]

== Container 
.container diagram example
[source, script]
----
@startuml demo container view
!include https://raw.githubusercontent.com/plantuml/plantuml-stdlib/master/C4/C4_Container.puml
!include C4_helper.iuml

%set_variable_value("$INCLUDE_DESC", "Y")

Title Sample Container View
Person(arch,"Architecht")
Person(eng,"Engineer")
Container_Boundary(ms,"Modelling System") {
  $container(vsc)
  }
  $container(c4)
  }
  $container(c4_helper)
  }
}

 Container_Boundary(gut,"Github"){
    $container(arc)
    }
    Container(json,"spec file","json","design parameters")
  }

Container(product,"Product","tech","built to spec")

Rel_R(arch,vsc,"models specs")
Rel_L(eng,arc, "build specs")
Rel_R(eng,product,"ships")
Rel(vsc,arc,"publish to")
Rel_U(c4,vsc,"Extends")
Rel_R(c4_helper,json,"uses")
Rel_U(json,arc,"provide definitions")
Rel(c4,c4_helper,"Extends")

$container_list()
'Lay_D(ms,c4_containers)
ms ..[hidden]..c4_containers

SHOW_LEGEND()

@enduml
----

image::demo container view.svg[Container]

== Component 
.component diagram example
In this example there is a mix of components defined using the helper macro and normal C4 coded components.
[source, script]
----
@startuml demo component view
!includeurl https://raw.githubusercontent.com/plantuml/plantuml-stdlib/master/C4/C4_Component.puml
 !include C4_helper.iuml

Title C4 Model Helper Component View 
'%set_variable_value("$C4_LEVEL", "COMPONENT")
'%set_variable_value("$INCLUDE_DESC", "Y")

$container_boundary(git_c4_helper) 
	Component(c4ctxr, "Context Registry ", "json", "list of registered contexts")
	Component(c4conr, "Container Registry ", "json", "list of registered containers")
	Component(c4comr, "Component Registry ", "json", "list of registered components")
	Component(c4ctx, "Locate Context ", "script", "locates context by id and returns values")
	Component(c4con, "Locate Container", "script", "locates container by id and returns values")
	Component(c4com, "Locate Component", "script", "locates component by id and returns values")
	Component(c4ctxl, "Context Legend ", "script", "creates a legend using the context registery")
	Component(c4conl, "Container Legend ", "script", "creates a legend using the container registery")
	Component(c4coml, "Component Legend ", "script", "creates a legend using the component registery")
}

Rel_Up(c4ctx, c4ctxr, "get by context id")
Rel_Up(c4ctxl, c4ctx, "get all")
Rel_Up(c4con, c4conr, "get by container id")
Rel_Up(c4conl, c4con, "get all")
Rel_Up(c4com, c4comr, "get by component id")
Rel_Up(c4coml, c4com, "get all")
Rel_Left(c4com, c4con, "get container by id")
Rel_Left(c4con, c4ctx, "get context by id")
@enduml
----

image::component_view.svg[Component]


== Usage Notes

An updated C4 Code Snippet is included which cater for the new helper routines introduced and sample json files.
The following variable are used

[options="header",cols="<.<2,<.<1, <.<4"]
|===
|Variable|Value|Behaviour
| $c4_diagram| diagram identifer eg. enterprise | Displays C4 Diagram
.3+|$C4_LEVEL|CONTEXT| Container objects will have the link as per the container registary
|CONTAINER|Container objects will have a link based on the assocated context identifier. Component objects will contain a link based on teh component registry.
|COMPONENT|Components will link back to the associated container. 
| $INCLUDE_DESC| Y | Includes description of object from respective registry. If the variable is not set or initialised to another value, descriptions are not shown.
| SHOW_TABLE() | | Displays C4 elements for the designated diagram which includes a list of diagrams this element also appears in. |
|===

