@startuml demo context view
!include https://raw.githubusercontent.com/plantuml/plantuml-stdlib/master/C4/C4_Container.puml
!include C4_helper.iuml

%set_variable_value("$INCLUDE_DESC", "Y")

Title Sample Context View
Person(arch,"Architecht")
Person(eng,"Engineer")

$container(ms)
}
$container(github)
}
'new product pending registeration
Container(product,"Product","tech","built to spec")

Rel_R(arch,ms,"models specs using")
Rel_R(ms,github,"push to")
Rel_L(eng,github, "get build specs")
Rel_R(eng,product,"ships")


SHOW_LEGEND()

@enduml

